POST http://localhost:5501/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Joe",
    "email": "johndoe@mail.com",
    "password": "qwertyu",
    "isSubscribed": true
}